version: "3.7"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgresql
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./.data/docker/postgresql:/var/lib/postgresql
    ports:
      - "5434:5432"
    networks:
      - server_network

networks:
  server_network:
    driver: bridge